### ISSUE TITLE
Consider relicensing

### ISSUE THREAD

**Issue by prologic** [no-gravity/html_editor#2]
Similar to https://github.com/kevquirk/simple.css/issues/2 for the same sets of reasons.

**Comment by no-gravity** [comment]
The GPL has proven very useful and the gist of it (You can share modifications of this if you share them with everyone) seems reasonable. Why would you prefer another license?

**Comment by prologic** [comment]
> The GPL has proven very useful and the gist of it (You can share modifications of this if you share them with everyone) seems reasonable. Why would you prefer another license?

I don't want to get into an argument with you over license choices, there are lots of guides, documentation and tools out there that help you choose the best license that suits your needs and requirements, such as the one I linked to by [Github](https://choosealicense.com/).

I can however say this, I more than often avoid choosing to use any GPL* license code or tools within my own project(s) (_where I can help it_) as much as humanly possible. Why? Because GPL* is far too restrictive for my tastes. For example if I were to use your "thing" and you held me to your license (GPL), that's unnecessary work for me, plus I would feel "obliged" rather than the other way around where I would contribute back (permissive) because that's the nice thing to do.

You do as you wish.

**Comment by no-gravity** [comment]
I think the GPL is more then fair in this regard. You can use and modify the software as you wish and only if you distribute it to someone, you are required to contribute back.
